### ISSUE TITLE
labelme2coco.py crash when just contines __ignore__ label

### ISSUE THREAD

**Issue by withkun** [labelmeai/labelme#1212]
### Provide environment information

(DET2) D:\FPCs>python --version
Python 3.9.13

(DET2) D:\FPCs>pip list labelme
Package                 Version            Editable project location
----------------------- ------------------ --------------------------
labelme                 5.0.5

### What OS are you using?

windows11

### Describe the Bug

(DET2) D:\FPCs>python D:/DeepLearning/labelme/examples/instance_segmentation/labelme2coco.py --labels classes.txt 000003 labels
Creating dataset: labels
Generating dataset from: 000003\dog.json
Traceback (most recent call last):
  File "D:\DeepLearning\labelme\examples\instance_segmentation\labelme2coco.py", line 209, in <module>
    main()
  File "D:\DeepLearning\labelme\examples\instance_segmentation\labelme2coco.py", line 184, in main
    labels, captions, masks = zip(
ValueError: not enough values to unpack (expected 3, got 0)

### Expected Behavior
Skip the label file

### To Reproduce
1. Just set __ignore__ label of an image
2. Create classes.txt file
3. run labelme2coco.py

**Comment by withkun** [comment]
label file of dog.json 
{
  "version": "5.0.5",
  "flags": {},
  "shapes": [
    {
      "label": "__ignore__",
      "points": [
        [
          1248.0740740740741,
          445.7530864197531
        ],
        [
          1586.3456790123457,
          1012.4197530864197
        ]
      ],
      "group_id": null,
      "shape_type": "rectangle",
      "flags": {}
    }
  ],
  "imagePath": "dog.png",
  "imageData": null,
  "imageHeight": 1152,
  "imageWidth": 2048
}

**Comment by HUBUwg96** [comment]
how to deal with？

**Comment by withkun** [comment]
> 

I think it is a bug when run labelme2coco.py on empty Label file

**Comment by qinli-jian** [comment]
The solution is here: https://github.com/labelmeai/labelme/issues/774

**Comment by withkun** [comment]
The solution is here: [https://github.com/labelmeai/labelme/issues/774#]
